import type { Car, Brand } from "@/types/car"

export const brands: Brand[] = [
  {
    id: "ferrari",
    name: "Ferrari",
    logo: "/images/ferrari.jpg",
    description: "Italian luxury sports car manufacturer",
    founded: 1947,
    country: "Italy",
  },
  {
    id: "lamborghini",
    name: "Lamborghini",
    logo: "/images/Lamborghini EVO.jpg",
    description: "Italian luxury sports car manufacturer",
    founded: 1963,
    country: "Italy",
  },
  {
    id: "porsche",
    name: "Porsche",
    logo:  "/images/Porsche.jpg",
    description: "German luxury sports car manufacturer",
    founded: 1931,
    country: "Germany",
  },
  {
    id: "tesla",
    name: "Tesla",
    logo: "/images/Tesla.jpg",
    description: "American electric vehicle manufacturer",
    founded: 2003,
    country: "USA",
  },
  {
    id: "bmw",
    name: "BMW",
    logo: "/images/BMW.jpg",
    description: "German luxury vehicle manufacturer",
    founded: 1916,
    country: "Germany",
  },
  {
    id: "mercedes",
    name: "Mercedes-Benz",
    logo: "/images/Mercedes.jpg",
    description: "German luxury vehicle manufacturer",
    founded: 1926,
    country: "Germany",
  },
]

export const cars: Car[] = [
  {
    id: "ferrari-f8",
    brand: "Ferrari",
    model: "F8 Tributo",
    year: 2024,
    price: 280000,
    originalPrice: 320000,
    image: "/images/ferrari%20Tributo.jpg",
    images: [
      "/images/ferrari%20Tributo.jpg",
      "/images/ferrari.jpg",
      "/images/TeslaS.jpg",
      "/images/Porsche911turbo.jpg",
    ],
    category: "sport",
    specs: {
      engine: "3.9L Twin-Turbo V8",
      power: "710 HP",
      acceleration: "0-100 km/h in 2.9s",
      topSpeed: "340 km/h",
      fuelType: "Gasoline",
      transmission: "7-Speed Dual-Clutch",
      drivetrain: "RWD",
    },
    features: ["Carbon Fiber Body", "Racing Seats", "Advanced Aerodynamics", "Launch Control"],
    description:
      "The Ferrari F8 Tributo is a mid-engine sports car that represents the pinnacle of Ferrari's V8 engineering.",
    isNew: true,
    isFeatured: true,
    discount: 12,
  },
  {
    id: "lamborghini-huracan",
    brand: "Lamborghini",
    model: "Huracán EVO",
    year: 2024,
    price: 250000,
    image: "/images/lamborghini-huracan-spyder.jpg",
    images: [
      "/images/lamborghini-huracan-spyder.jpg",
      "/images/Lamborghini%20EVO.jpg",
      "/images/ferrari.jpg",
      "/images/TeslaS.jpg",
    ],
    category: "sport",
    specs: {
      engine: "5.2L V10",
      power: "630 HP",
      acceleration: "0-100 km/h in 2.9s",
      topSpeed: "325 km/h",
      fuelType: "Gasoline",
      transmission: "7-Speed Dual-Clutch",
      drivetrain: "AWD",
    },
    features: [
      "All-Wheel Drive",
      "Dynamic Steering",
      "Performance Traction Control",
      "Lamborghini Dinamica Veicolo Integrata",
    ],
    description: "The Huracán EVO is the evolution of the most successful V10-powered Lamborghini ever.",
    isNew: true,
    isFeatured: true,
  },
  {
    id: "tesla-model-s",
    brand: "Tesla",
    model: "Model S Plaid",
    year: 2024,
    price: 135000,
    image: "/images/Tesla%20Praid.jpg",
    images: [
      "/images/Tesla%20Praid.jpg",
      "/images/TeslaS.jpg",
      "/images/Tesla.jpg",
      "/images/Porsche911turbo.jpg",
    ],
    category: "electric",
    specs: {
      engine: "Tri-Motor Electric",
      power: "1020 HP",
      acceleration: "0-100 km/h in 2.1s",
      topSpeed: "322 km/h",
      fuelType: "Electric",
      transmission: "Single-Speed",
      drivetrain: "AWD",
    },
    features: ["Autopilot", "17-inch Touchscreen", "Glass Roof", "Premium Audio"],
    description: "The fastest production sedan ever built, with tri-motor all-wheel drive and carbon fiber interior.",
    isNew: true,
    isFeatured: true,
  },
  {
    id: "porsche-911",
    brand: "Porsche",
    model: "911 Turbo S",
    year: 2024,
    price: 220000,
    image: "/images/Porsche911turbo.jpg",
    images: [
      "/images/Porsche911turbo.jpg",
      "/images/Porsche.jpg",
      "/images/ferrari.jpg",
      "/images/BMW.jpg",
    ],
    category: "sport",
    specs: {
      engine: "3.8L Twin-Turbo Flat-6",
      power: "640 HP",
      acceleration: "0-100 km/h in 2.7s",
      topSpeed: "330 km/h",
      fuelType: "Gasoline",
      transmission: "8-Speed PDK",
      drivetrain: "AWD",
    },
    features: ["Active Suspension", "Sport Chrono Package", "Ceramic Brakes", "Sport Exhaust"],
    description: "The ultimate 911, combining everyday usability with racetrack performance.",
    isNew: false,
    isFeatured: true,
  },
  {
    id: "bmw-m8",
    brand: "BMW",
    model: "M8 Competition",
    year: 2024,
    price: 180000,
    image: "/images/BMW.jpg",
    images: ["/images/BMW.jpg", "/images/Mercedes.jpg"],
    category: "luxury",
    specs: {
      engine: "4.4L Twin-Turbo V8",
      power: "617 HP",
      acceleration: "0-100 km/h in 3.2s",
      topSpeed: "305 km/h",
      fuelType: "Gasoline",
      transmission: "8-Speed Automatic",
      drivetrain: "AWD",
    },
    features: ["M xDrive", "Carbon Fiber Roof", "Harman Kardon Audio", "Adaptive M Suspension"],
    description: "The most powerful BMW M car ever, combining luxury with track-focused performance.",
    isNew: true,
    isFeatured: false,
  },
  {
    id: "mercedes-amg-gt",
    brand: "Mercedes-Benz",
    model: "AMG GT 63 S",
    year: 2024,
    price: 200000,
    image: "/images/Mercedes.jpg",
    images: ["/images/Mercedes.jpg", "/images/BMW.jpg"],
    category: "luxury",
    specs: {
      engine: "4.0L Twin-Turbo V8",
      power: "630 HP",
      acceleration: "0-100 km/h in 3.2s",
      topSpeed: "315 km/h",
      fuelType: "Gasoline",
      transmission: "9-Speed Automatic",
      drivetrain: "AWD",
    },
    features: ["AMG Performance 4MATIC+", "Active Aerodynamics", "Burmester Audio", "AMG Ride Control"],
    description: "A four-door coupe that doesn't compromise on performance or luxury.",
    isNew: false,
    isFeatured: false,
  },
]
